### ISSUE TITLE
Mobile環境のVisualizerにてnextpageが指すhrefが正しくない

### ISSUE THREAD

**Issue by homuraction** [mfakane/Megalopolis#1]
# 起こっていること
Mobile環境で検索を行う際に全文検索以外の検索時、「次のページ」を押すと作品が表示されなくなる

# 原因
「次のページ」に指定されているhrefの構成が
```
array("query" => IndexHandler::param("query"), "p" => $h->page + 1)
```
https://github.com/mfakane/Megalopolis/blob/dff38a8ab25b758e8bb7ea1a621cf33983e9e54e/req/Visualizer/mobile/Index/Index.php#L114
となっており、defaultのquery以外のモードで動作しなくなっているため

# 提案
下記の様に修正する
```
array("query" => $search, "mode" => $searchMode, "p" => $h->page + 1)
```

**Comment by mfakane** [comment]
ご報告ありがとうございます！
修正のため、提案をそのまま採用させていただきました。ありがとうございました！
